"""empty message

Revision ID: 6d4997c58be9
Revises: c82cdf2fbc4b
Create Date: 2023-09-03 14:39:41.278831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4997c58be9'
down_revision: Union[str, None] = 'c82cdf2fbc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Mytest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mytest',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Mytest_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Mytest_pkey')
    )
    # ### end Alembic commands ###
