"""empty message

Revision ID: 6da7b09e5222
Revises: 
Create Date: 2023-09-07 22:55:23.173484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da7b09e5222'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_time_operation', sa.String(), nullable=False),
    sa.Column('data_payment', sa.String(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('status_operation', sa.String(), nullable=False),
    sa.Column('sum_operation', sa.String(), nullable=False),
    sa.Column('currency_operation', sa.String(), nullable=False),
    sa.Column('sum_payment', sa.String(), nullable=False),
    sa.Column('currency_payment', sa.String(), nullable=False),
    sa.Column('cashback', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('mss', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bonus_cashback', sa.String(), nullable=False),
    sa.Column('rounding_invest', sa.String(), nullable=False),
    sa.Column('rounding_operation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
