"""empty message

Revision ID: 3f4fe80886d1
Revises: 
Create Date: 2023-09-10 11:34:59.483647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4fe80886d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_time_operation', sa.DateTime(), nullable=False),
    sa.Column('data_payment', sa.DateTime(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('status_operation', sa.Boolean(), nullable=False),
    sa.Column('sum_operation', sa.Numeric(), nullable=False),
    sa.Column('currency_operation', sa.String(), nullable=False),
    sa.Column('sum_payment', sa.Numeric(), nullable=False),
    sa.Column('currency_payment', sa.String(), nullable=False),
    sa.Column('cashback', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('mss', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('bonus_cashback', sa.Numeric(), nullable=False),
    sa.Column('rounding_invest', sa.Numeric(), nullable=False),
    sa.Column('rounding_operation', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
